### ISSUE TITLE
Resolve issues with sparse-develop before new PR

### ISSUE THREAD

**Issue by ashermancinelli** [LLNL/hiop#113]
This issue is to coordinate development of branch `sparse-develop` before being merged with branch `develop`. The following issues must be resolved before `sparse-develop` can be merged.

- [ ] CUDA/Pthreads library conflicts #111 
- [x] Operator overloading error when building test drivers #110
- [x] sparse-develop branch lacking implementations of RAJA functions #109
- [x] Fix CI configuration and install proper dependencies on test machines #107
- [ ] Add RAJA implementations for new methods added to the `hiopMatrixSparse` interface in `sparse-develop` branch
- [x] Passing CI on all platforms

@pelesh @nychiang @cnpetra Please add additional blockers that must be resolved for `sparse-develop` to be merged into `develop`.

**Comment by cnpetra** [comment]
Since sparse-develop blocks a couple of other developments, we will do the following if #110 and #109 are fixed and sparse-develop (manually) passes the existing tests with RAJA, UMPIRE, and GPU on, then it should be merged regardless of CI issues. A follow-on PR will be provide RAJA implementation and unit tests for the newly added methods to check all the remaining non-CI "boxes".

**Comment by pelesh** [comment]
I think CI will be fixed before `sparse-develop` is ready to merge. The only major outstanding item is installing STRUMPACK on test machines because of its many dependencies. We can set up tests with HSL with very minor modifications to the existing configuration. 

I agree we should merge CPU only version of sparse strategy for as long as it does not break other code.

**Comment by cnpetra** [comment]
STRUMPACK is optional and, also, HiOp-STRUMPACK code is a bit experimental right now (will be revisited later on) to the extent that none of the tests are based on it. 

If you decide to install STRUMPACK , it is worth looking into building it without MPI and Scalapack support, which will make it easier to build STRUMPACK. It should work with HiOp both in MPI and non-MPI mode.

**Comment by ashermancinelli** [comment]
`sparse-develop` was merged in #120
