### ISSUE TITLE
improve the numerical stability 

### ISSUE THREAD

**Issue by nychiang** [LLNL/hiop#180]
Improve the HiOp numerical stability:
- [x]  duals initialization and update
- [x]  Scale the problem before solving the problem #177 
- [x]  Adjust variable bound when the corresponding slack variable is too small #178
- [x]  Slightly relax bound before solving the problem #179
