### ISSUE TITLE
Make HiOp xSDK compliant

### ISSUE THREAD

**Issue by pelesh** [LLNL/hiop#99]
It seems that HiOp already meets most if not all xSDK compliance policies. It would be good to create [xSDK compliance policy compatibility document](https://github.com/xsdk-project/xsdk-policy-compatibility/blob/master/template.md) for HiOp and fix outstanding compatibility issues (if any). Next, we could apply for HiOp to be included in [xSDK](https://xsdk.info/).

Completing these will satisfy mandatory compliance requirements:
- [x] M1. Support portable installation through Spack.
- [x] M2. Provide a comprehensive test suite for correctness of installation verification.
- [x] M3. Employ user-provided MPI communicator (no MPI_COMM_WORLD). Don't assume a full MPI 3 implementation without checking. Provide an option to prevent any changes to MPI error-handling if it is changed by default.
- [x] M4. Give best effort at portability to key architectures (standard Linux distributions, GNU, Clang, vendor compilers, and target machines at ALCF, NERSC, OLCF).
- [x] M5. Provide a documented, reliable way to contact the development team.
- [x] M6. Respect system resources and settings made by other previously called packages (e.g. signal handling).
- [x] M7. Come with an open source (BSD style) license.
- [x] M8. Provide a runtime API to return the current version number of the software (added with #148).
- [x] M9. Use a limited and well-defined symbol, macro, library, and include file name space.
- [x] M10. Provide an xSDK team accessible repository (not necessarily publicly available).
- [x] M11. Have no hardwired print or IO statements that cannot be turned off.
- [x] M12. For external dependencies, allow installing, building, and linking against an outside copy of external software.
- [x] M13. Install headers and libraries under <prefix>/include and <prefix>/lib.
- [x] M14. Be buildable using 64 bit pointers. 32 bit is optional.
- [x] M15. All xSDK compatibility changes should be sustainable.
- [x] M16. Have a debug build option.

Following are recommended xSDK policies:
- [x] R1. Have a public repository.
- [x] R2. Possible to run test suite under valgrind in order to test for memory corruption issues (added in #146).
- [x] R3. Adopt and document consistent system for error conditions/exceptions.
- [x] R4. Free all system resources acquired as soon as they are no longer needed.
- [x] R5. Provide a mechanism to export ordered list of library dependencies (added with #148).
- [ ] R6. Document versions of packages that it works with or depends upon, preferably in machine-readable form.
- [x] R7. Have README, SUPPORT, LICENSE, and CHANGELOG files in top directory.
- [x] R8. Provide sufficient documentation to support use and further development.

CC @ashermancinelli

**Comment by pelesh** [comment]
Per [xSDK FAQ](http://xsdk.info/faq/) there are two categories of xSDK packages:
1. **Compatible**: I think HiOp is already there, we just need to get certified.
2. **Member**: This requires package to be compatible and dependent (or dependency) of other xSDK package(s). With Magma and STRUMPACK as its dependencies, HiOp meets this requirement, as well. The missing piece is CI for Magma and STRUMPACK interfaces. This should not be difficult to add.

**Comment by cnpetra** [comment]
M1 needs work. All the remaining unchecked ones are supported, but will check them after I double check HiOp supports them

**Comment by pelesh** [comment]
M11 may need some work, as well. One may argue that statements like
```c++
assert(m==n && "Not square matrix");
```
do not allow you to redirect error output.

**Comment by ashermancinelli** [comment]
> M11 may need some work, as well. One may argue that statements like
> 
> ```c++
> assert(m==n && "Not square matrix");
> ```
> 
> do not allow you to redirect error output.

We could use exceptions instead, in which case the hiopLogger class could set some static variable that determines where error output ends up. This would also allow our tests to test for failure cases, which we currently don't have at all. Thoughts?

**Comment by pelesh** [comment]
@ashermancinelli I think using exceptions is a more flexible solution. It would better address R3, as well.

**Comment by cnpetra** [comment]
> M11 may need some work, as well. One may argue that statements like
> 
> ```c++
> assert(m==n && "Not square matrix");
> ```
> 
> do not allow you to redirect error output.

disagree, those can be easily turned off by anyone who is smart enough to not run debug code in production.

**Comment by cnpetra** [comment]
> @ashermancinelli I think using exceptions is a more flexible solution. It would better address R3, as well.

there is error control and they could be more comprehensive no doubt. But switching to exceptions is for me a distraction, at least short term.

**Comment by ashermancinelli** [comment]
Update: Branch [xsdk-compliance-doc (linked here)](https://gitlab.pnnl.gov/exasgd/frameworks/exago/-/tree/xsdk-compliance-doc) contains a work-in-progress compliance document under the `doc` directory, to be updated by @vamatya

**Comment by ashermancinelli** [comment]
- M1: we already have nicholson's WIP spack package, I don't think that will take too much revision
- M5: Issue submission via github seems to count (https://github.com/xsdk-project/xsdk-policy-compatibility)
- M8: we can add an interface-level function to return version no.
- M12: cmake library discovery counts for this

**Comment by ashermancinelli** [comment]
Spack package is being actively developed by @nkoukpaizan - we can check this box and submit pr to spack when we're ready for official xsdk review.

**Comment by cnpetra** [comment]
closing this since we're in the review phase now.
